

spring:
  application:
    name: identity-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bookteria_identity
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8080
  servlet:
    context-path: /identity
